[package]
name = "miniprolog"
version = "0.1.0"
authors = ["dagit <dagitj@gmail.com>"]
build = "build.rs" # LALRPOP preprocessing

[dependencies]
rl-sys = "*"

[dependencies.lalrpop-util]
git = "https://github.com/nikomatsakis/lalrpop.git"
#version = "*"

[build-dependencies.lalrpop]
git = "https://github.com/nikomatsakis/lalrpop.git"
#version = "*"
