[package]
name = "miniprolog"
version = "0.1.0"
authors = ["dagit <dagitj@gmail.com>"]
build = "build.rs" # LALRPOP preprocessing

[profile.dev]
opt-level = 2
debug = true

[dependencies]
rustyline   = "*"
regex       = "*"
lazy_static = "*"
ctrlc       = "*"
gc          = "*"
gc_derive   = "*"

[dependencies.lalrpop-util]
version = "0.14"

[build-dependencies.lalrpop]
version = "0.14"
