[package]
name = "miniprolog"
version = "0.1.0"
authors = ["dagit <dagitj@gmail.com>"]
build = "build.rs" # LALRPOP preprocessing

[dependencies]
rustyline   = "*"
regex       = "*"
lazy_static = "*"
ctrlc       = "*"

[dependencies.lalrpop-util]
version = "*"

[build-dependencies.lalrpop]
version = "*"
